name: Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * *"

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Set Up
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: go run cmd/job/main.go
