name: Job

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 13 * * *"

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Set Up
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
          echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> .env

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: go run cmd/job/main.go
